name = "dzn-auto-update-worker"
main = "workers/dzn-auto-update-worker.ts"
compatibility_date = "2026-05-13"

[triggers]
crons = ["* * * * *"]

[vars]
DZN_APP_URL = "https://dzn-network.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "dzn_network_db"
database_id = "37515c66-2787-49e4-8568-a461517e975e"
