import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const advancedSource = readFileSync("functions/_lib/advanced-leaderboards.ts", "utf8");
const publicAdvancedApi = readFileSync("functions/api/public/leaderboards/advanced.ts", "utf8");
const publicServerAdvancedApi = readFileSync("functions/api/public/servers/[serverId]/leaderboards.ts", "utf8");
const publicExplorationApi = readFileSync("functions/api/public/servers/[serverId]/exploration.ts", "utf8");
const ownerAdvancedApi = readFileSync("functions/api/servers/[serverId]/dashboard/advanced-stats.ts", "utf8");
const previewSeed = readFileSync("scripts/seed-advanced-showcase-preview.ts", "utf8");
const advancedEntitlements = readFileSync("functions/_lib/advanced-showcase-entitlements.ts", "utf8");
const leaderboardsPage = readFileSync("app/leaderboards/page.tsx", "utf8");

assert.match(advancedSource, /queryServerStatsSnapshot/);
assert.match(advancedSource, /queryBoundedServerStatsFallback/);
assert.match(advancedSource, /queryPositionSamples/);
assert.match(advancedSource, /Global travel and exploration ranks remain unavailable until durable plan-neutral aggregates/);
assert.match(advancedSource, /SERVER_ADVANCED_EVENT_SAMPLE_LIMIT = 6_000/);
assert.match(advancedSource, /cachedAdvancedPayload/);
assert.match(advancedSource, /raw player coordinates and exact routes are not exposed/i);
assert.doesNotMatch(advancedSource, /serverBoard\([^\n]+, "pro"/);
assert.match(advancedEntitlements, /globalAdvancedBoards:\s*true/);
assert.doesNotMatch(advancedEntitlements, /key:\s*"global_showcase"/);
assert.doesNotMatch(leaderboardsPage, /Global server boards for combat, builds, hybrid activity, travel, and exploration/);
assert.doesNotMatch(publicAdvancedApi, /^\s*"(?:travel|exploration)",$/m);
assert.match(advancedSource, /const canShowMapOverlay = access\.publicMapOverlay;/);
assert.doesNotMatch(advancedSource, /access\.public(?:MapOverlay|ExplorationSummary) \|\| ownerScoped/);
assert.match(advancedSource, /canShowMapOverlay \? exploration : \{ \.\.\.exploration, overlayCells: \[\] \}/);
assert.doesNotMatch(publicExplorationApi, /position_x|position_y|pos_x|pos_y/);
assert.doesNotMatch(publicServerAdvancedApi, /position_x|position_y|pos_x|pos_y/);
assert.match(publicAdvancedApi, /publicAccessCacheHeaders/);
assert.match(publicAdvancedApi, /withRouteBudget/);
assert.match(publicAdvancedApi, /Advanced Showcase is temporarily unavailable/);
assert.match(publicAdvancedApi, /fallback_reason: "advanced_live_query_failed_no_snapshot"/);
assert.doesNotMatch(publicAdvancedApi, /position_x|position_y|pos_x|pos_y/);
assert.doesNotMatch(publicAdvancedApi, /publicApiErrorHeaders/);
assert.doesNotMatch(publicAdvancedApi, /status:\s*503/);
assert.match(publicServerAdvancedApi, /publicApiErrorHeaders/);
assert.doesNotMatch(publicServerAdvancedApi + publicExplorationApi, /publicAccessCacheHeaders/);
assert.match(ownerAdvancedApi, /requireServerOwnerOrDznAdmin/);
assert.match(ownerAdvancedApi, /unauthenticated/);
assert.doesNotMatch(ownerAdvancedApi, /max-age/);
assert.doesNotMatch(advancedSource, /queryServerEventCounts/);
assert.match(previewSeed, /local-preview only/i);
assert.match(previewSeed, /"--local"/);
assert.match(previewSeed, /must never run with --remote/);
assert.doesNotMatch(previewSeed, /\["wrangler",\s*"d1",\s*"execute",\s*"dzn_network_db",\s*"--remote"/);
assert.doesNotMatch(previewSeed, /DELETE\s+FROM/i);

console.log("Advanced leaderboard API safety tests passed.");
